##############################################################################
## Global configuration--parameters used in multiple scripts
###############################################################################

## Set your email to get notifications for slurm jobs
email: "beckandy@umich.edu"

## inputdir defines the directory containing the prepared VCF and .summary files
inputdir: "/net/bipolar/jedidiah/testpipe"

analysisdir: "/net/snowwhite/home/beckandy/research/smaug-smake"

##############################################################################
# set flags for which files to output when running augment_summary.pl script
##############################################################################
count_motifs: TRUE
expand_summ: TRUE

# binw defines the width of fixed bins in base pairs
binw: 1000000

##############################################################################
## Define location and naming convention of raw input vcfs, if we are using the
## 'makecopy' option in vcf_to_summary.pl
## rawvcfext defines the suffix of the raw vcfs we want to copy into inputdir
###############################################################################
rawvcfdir: "/net/bipolar/lockeae/final_freeze/snps/vcfs"
rawvcfext: "filtered.sites.modified.vcf.gz"

##############################################################################
## ped files containing sample info
###############################################################################
pedfile: "/net/wonderland/home/mattz/BRIDGES/FinalAnalysis/ped/BRIDGES_Assoc.20160226.ped"
plates: "/net/wonderland/home/mattz/BRIDGES/sampleIDs_plates.txt"
# qcped: "/net/bipolar/lockeae/final_freeze/snps/QC/final_freeze.merged.vcfast_vcfdiff_qplot.v2.txt"
qplotfile: "/net/bipolar/bridges/phenotype/qplotstats.txt"
vcfastfile: "/net/bipolar/lockeae/final_freeze/snps/QC/vcfast/final.snps.vcfast.merged.txt"
contamfile: "/net/bipolar/bridges/QC/contamination/clean/contest.txt"
phenofile: "/net/wonderland/home/mattz/BRIDGES/pheno.txt"
pcfile: "/net/wonderland/home/mattz/BRIDGES/Assoc/StudyPCs/BRIDGES_sample_PCA.eigen.evec"

##############################################################################
## Info for processing glf files
###############################################################################
## List of samples, one per line
samples: "/net/bipolar/lockeae/final_freeze/list.txt"

## Directory containing raw glf files
glfdir: "/net/bipolar/bridges/sequencedata/umake/glfs/samples"
