name: smaug
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - andyb262
dependencies:
  - bcftools=1.3.1
  - vcftools=0.1.16
  - python=3.5.1
  - snakemake
  - pyyaml
  - r-base
  - r-broom
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-RColorBrewer
  - r-MASS
  - r-speedglm
  - r-boot
  - r-devtools
  - r-psych
  - r-lmtest
  - r-fmsb
  - r-cowplot
  - r-hexbin
  - r-stringr
  - r-gridbase
  - r-gridextra
  - r-gtable
  - samtools-hybrid
  - perl
  - perl-yaml-libyaml
  - perl-math-round
  - ftputil
  - ucsc-bigwigtowig
