channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - vcftools=0.1.16
  - graphviz=2.38.0
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - r=3.5.0
  - r-broom
  - r-ggplot2=3.0.0
  - r-dplyr=0.7.5
  - r-tidyr=0.8.1
  - r-RColorBrewer
  - r-MASS=7.3_50
  - r-speedlgm=0.3_2
  - r-boot=1.3_20
  - r-devtools=1.13.6
  - r-psych=1.8.4
  - r-lmtest=0.9_36
  - r-fmsb=0.6.3
  - r-cowplot=0.9.3
  - r-hexbin=1.27.2
  - r-stringr=1.3.1
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.2.0
